# AGH Image Viewer
Alias /agh /var/www/html/agh

<Directory /var/www/html/agh>
    Options -Indexes +FollowSymLinks
    AllowOverride None
    AuthType Basic
    AuthName "AGH Image Viewer"
    AuthBasicProvider file
    AuthUserFile /etc/apache2/.agh-viewer.htpasswd
    Require valid-user
    FallbackResource /agh/index.html
</Directory>

<Location "/agh/api">
    AuthType Basic
    AuthName "AGH Image Viewer"
    AuthBasicProvider file
    AuthUserFile /etc/apache2/.agh-viewer.htpasswd
    Require valid-user
    RequestHeader set X-Remote-User "expr=%{REMOTE_USER}"
</Location>

ProxyPass /agh/api/ http://127.0.0.1:5055/agh/api/ nocanon
ProxyPassReverse /agh/api/ http://127.0.0.1:5055/agh/api/
ProxyPass /agh !
ProxyPass /agh/ !
